# Generated by Django 4.2.6 on 2023-10-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdvxLibraryBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='alternateTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
