# Generated by Django 4.2.6 on 2023-10-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdvxLibraryBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songresult',
            options={'verbose_name': 'song result', 'verbose_name_plural': '1. song result'},
        ),
        migrations.AlterField(
            model_name='songresult',
            name='release_date',
            field=models.DateField(),
        ),
    ]
