# Generated by Django 4.2.6 on 2023-10-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdvxLibraryBackend', '0002_song_alternatetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='difficultyName',
            field=models.CharField(choices=[('NOVICE', 'Novice'), ('ADVANCED', 'Advanced'), ('EXHAUST', 'Exhaust'), ('INFINITE', 'Infinite'), ('GRAVITY', 'Gravity'), ('MAXIMUM', 'Maximum'), ('HEAVENLY', 'Heavenly'), ('VIVID', 'Vivid'), ('EXCEED', 'Exceed')], max_length=10),
        ),
    ]
