# Generated by Django 4.2.6 on 2023-10-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdvxLibraryBackend', '0004_song_songdifficulties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songDifficulties',
        ),
    ]
